version: "3.3"

services:
  # Jenkinsコンテナ
  jenkins:
    # Dockerfileからビルドする
    build:
      context: ./
      dockerfile: Dockerfile

    # 
    links:
      - jetty

    # コンテナ内のポートをホストに公開する
    # 書式 HOST:CONTAINER
    ports:
      # Jenkins画面のポートを同じ番号でホストに公開する
      - 8080:8080

    # 
    volumes:
      - ./jenkins_home:/var/jenkins_home

  # Jettyコンテナ
  jetty:
    # Dockerfileからビルドする
    build:
      context: ./
      dockerfile: jetty.Dockerfile

    # コンテナ内のポートをホストに公開する
    # 書式 HOST:CONTAINER
    ports:
      # Jettyのポートをランダムな値でホストに公開する
      - 8080
