version: "3.3"

services:
  # Jenkinsコンテナ
  jenkins:
    # Dockerfileからビルドする
    build: ./jenkins

    # 
    links:
      - jetty

    # コンテナ内のポートをホストに公開する
    # 書式 HOST:CONTAINER
    ports:
      # Jenkins画面のポートを同じ番号でホストに公開する
      - 8080:8080

    # 
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  # Jettyコンテナ
  jetty:
    # Dockerfileからビルドする
    build: ./jetty

    # コンテナ内のポートをホストに公開する
    # 書式 HOST:CONTAINER
    ports:
      # JettyのポートをJenkinsと重複しない値でホストに公開する
      - 8180:8080
